# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import asr_api_pb2 as asr__api__pb2


class SttServiceStub(object):
    """Сервис распознавания речи
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSupportedModelsInfo = channel.unary_unary(
                '/vox.asr.SttService/GetSupportedModelsInfo',
                request_serializer=asr__api__pb2.Empty.SerializeToString,
                response_deserializer=asr__api__pb2.ModelsResponse.FromString,
                )
        self.Recognize = channel.unary_unary(
                '/vox.asr.SttService/Recognize',
                request_serializer=asr__api__pb2.RecognitionRequest.SerializeToString,
                response_deserializer=asr__api__pb2.RecognitionResponse.FromString,
                )
        self.StreamingRecognize = channel.stream_stream(
                '/vox.asr.SttService/StreamingRecognize',
                request_serializer=asr__api__pb2.StreamingRecognitionRequest.SerializeToString,
                response_deserializer=asr__api__pb2.StreamingRecognitionResponse.FromString,
                )


class SttServiceServicer(object):
    """Сервис распознавания речи
    """

    def GetSupportedModelsInfo(self, request, context):
        """Функция запроса списка поддерживаемых моделей
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recognize(self, request, context):
        """Функция для распознавания аудио целиком
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamingRecognize(self, request_iterator, context):
        """Функция поточного распознавания
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SttServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSupportedModelsInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSupportedModelsInfo,
                    request_deserializer=asr__api__pb2.Empty.FromString,
                    response_serializer=asr__api__pb2.ModelsResponse.SerializeToString,
            ),
            'Recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=asr__api__pb2.RecognitionRequest.FromString,
                    response_serializer=asr__api__pb2.RecognitionResponse.SerializeToString,
            ),
            'StreamingRecognize': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamingRecognize,
                    request_deserializer=asr__api__pb2.StreamingRecognitionRequest.FromString,
                    response_serializer=asr__api__pb2.StreamingRecognitionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vox.asr.SttService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SttService(object):
    """Сервис распознавания речи
    """

    @staticmethod
    def GetSupportedModelsInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vox.asr.SttService/GetSupportedModelsInfo',
            asr__api__pb2.Empty.SerializeToString,
            asr__api__pb2.ModelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vox.asr.SttService/Recognize',
            asr__api__pb2.RecognitionRequest.SerializeToString,
            asr__api__pb2.RecognitionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamingRecognize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/vox.asr.SttService/StreamingRecognize',
            asr__api__pb2.StreamingRecognitionRequest.SerializeToString,
            asr__api__pb2.StreamingRecognitionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
